### ISSUE TITLE
Bug: Wrong dollar value in crowdloan section

### ISSUE THREAD

**Issue by kianenigma** [TalismanSociety/talisman-web#122]
Hi, great web-app and quite useful! 

I noticed that the dollar value next to the crowdloan section is either wrong for me or non-sensical. It is orders of magnitude higher than the sum of the KSM's dollar value that is locked in crowdloans.

**Comment by alecdwm** [comment]
Hey @kianenigma, this should be fixed. 
Could please you check https://app.talisman.xyz and confirm for me that the amounts are now showing correctly?

**Comment by kianenigma** [comment]
Yup, fixed now. Thanks!
