### ISSUE TITLE
Feature request: Allow importing Moonbeam accounts without exposing any private keys

### ISSUE THREAD

**Issue by kianenigma** [TalismanSociety/talisman-web#124]
I am not sure if it is possible, but the current recommended approach of importing the private key into the apps-ui i simply too risky for a mere portfolio inspection. Ideally, you would be able to see your moonbeam funds only by exposing your public key, similar to what you can do with the Polkadot-Js extension and QR-signed accounts.

**Comment by helloitsbirdo** [comment]
This should be resolved now as we have added full EVM support (inc moonbeam) into the wallet.
Any wallet can inject EVM wallet addresses without the need for importing a private key.
