### ISSUE TITLE
Crowdloans require copy

### ISSUE THREAD

**Issue by daniel-flex** [TalismanSociety/talisman-web#136]
https://app.talisman.xyz/crowdloans/parallel
https://app.talisman.xyz/crowdloans/manta

@juliuscarvajal

**Comment by MignightSwami** [comment]
parallel: `Parallel's mission is to innovate and bring DeFi to the next level.
We are creating the most secure and easy-to-use decentralized platform to empower
everyone access to financial services`

**Comment by MignightSwami** [comment]
manta: `Manta Network is a private layer built for the entire Polkadot ecosystem. Built on the Substrate framework, Manta Network is natively compatible with other projects and parachain assets including wrapped major cryptoassets.`

**Comment by juliuscarvajal** [comment]
@MignightSwami I assume that the above is `info`? Please provide `subtitle`. Cheers

**Comment by juliuscarvajal** [comment]
Fixed
