### ISSUE TITLE
Rehydrate portfolio crowdloan contribution on successful contribution

### ISSUE THREAD

**Issue by SwamiTLSM** [TalismanSociety/talisman-web#138]
We should requery for crowdloan contributions after successfully contributing - may require a delay of 5-10 seconds?

Another option is to manually inject the crowdloan contribution into the store, so it's there, then manually run the query after 5-10 sec. 

Currently it's rehydrating at a set interval, we could probably remove that and just refresh after contribution.

**Comment by MignightSwami** [comment]
Update: contributed to moonbeam and the updated balance didn't automatically appear on the accounts page, even after waiting for a few minutes.

After refresh it was there.
