### ISSUE TITLE
[BUG] KSM crowdloans show DOT as currency when account holds only DOT

### ISSUE THREAD

**Issue by phillux** [TalismanSociety/talisman-web#175]
![image](https://user-images.githubusercontent.com/6450379/144250892-a8f4a24f-16af-4726-b117-66b3367b95af.png)

When a use connects to Talisman via the polkadot-js extension, and the account holds DOT but no KSM, then the user tries to contribute to a KSM crowdloan, the Talisman web app allows DOT to be added in the UI and enables the green "contribute" button.

Relay chain crowdloans should only allow the native token to each respective network. 

I have not tried to see what happens when the user clicks contribute, but the user should not even be allowed to make it to this point.

(great work on the wallet btw!)

**Comment by juliuscarvajal** [comment]
Closing as native tokens shows up in the contribute modal.
