### ISSUE TITLE
[BUG] Buy via Ramp frame shows scrollbars on Firefox

### ISSUE THREAD

**Issue by phillux** [TalismanSociety/talisman-web#176]
![image](https://user-images.githubusercontent.com/6450379/144251893-147b2334-20fb-426f-afd7-fb948fdab9aa.png)

When a user of Firefox (linux) clicks "buy" in the top-right corner, scroll bars appear that add no value or usability.

(love the wallet!)

**Comment by helloitsbirdo** [comment]
likely this will be deprecated as we change onramp provider

**Comment by JAhimaz** [comment]
Onramp provider has been changed :)
