### ISSUE TITLE
Unable to interact with any chain, sometime after a long session

### ISSUE THREAD

**Issue by tien** [TalismanSociety/talisman-web#327]
## Reproduction

Happen intermittently after having the app open for a long session.

## Symptoms

- Multiple errors `FATAL: Unable to initialize the API: disconnected from wss://[CHAIN_WS_URL]: 1006:: Abnormal Closure` from different chains, when inspecting the browser console log.
- Unable to read or perform any action with any chain across different DApps

## Temporary resolution

Closing the browser completely and start a new session (opening different tab or refreshing doesn't help)

## Similar issues

polkadot-js/api#3960
polkadot-js/api#1436

**Comment by forgetso** [comment]
For what its worth, if you're on `localhost` and you use `wss` as the protocol then you will continuously hit this error. Use `ws` instead for `localhost` chains.

**Comment by SwamiTLSM** [comment]
possibly related to #351

**Comment by SwamiTLSM** [comment]
We'll need to do a deep dive into why this is happening, currently looks like when there's 2 tabs open with the same sockets open. Is it the RPC rejecting the connection or the browser?

**Comment by JAhimaz** [comment]
This will fix after the balance lib improvement. Do close when done @alecdwm

**Comment by alecdwm** [comment]
Afaik this was solved by our new RPC management in the ChainConnector, but it's then double-y solved by the integration between the portal and the wallet's RPC connections.

If seen again, please re-open this issue!
