### ISSUE TITLE
Multiple opened tab caused the page to load either really long or forever

### ISSUE THREAD

**Issue by tien** [TalismanSociety/talisman-web#351]
# Current behaviour

- First tab will load instantly
- Subsequent tabs will load either very slowly or forever
- Closing all others older tab would make the current tab finish loading

**Comment by tien** [comment]
cc @helloitsbirdo

**Comment by helloitsbirdo** [comment]
just on nom pools page

**Comment by JAhimaz** [comment]
Duplicate of #327, will close.
