### ISSUE TITLE
add `extensionUnavailable` to common components

### ISSUE THREAD

**Issue by jonathanpdunne** [TalismanSociety/talisman-web#375]
The `extensionUnavailable` component is defined in 4 seperate places: 

- `/archetypes/Wallet/Assets.tsx`
- `/archetypes/Wallet/Crowdloans.tsx`
- `/routes/NFTsPage.tsx`
- `/routes/TransactionHistory.tsx`

Let's define this as it's own molecule & import from there (assuming we want to keep this pattern & nomanclature)

**Comment by alecdwm** [comment]
Closing as we don't use this component anymore!
