### ISSUE TITLE
accounts.unsubscribe() flagging console.errror

### ISSUE THREAD

**Issue by rossbulat** [TalismanSociety/talisman-web#393]
From 17/11/22 I am getting the following error when subscribing to Talisman accounts from the extension:

<img width="347" alt="Screenshot 2022-11-17 at 12 41 02" src="https://user-images.githubusercontent.com/13929023/202438072-d56ce31c-f59f-4e62-8dce-83dedcad816d.png">

This is occurring once accounts are subscribed (unsubscribe should not be triggered).

If more context is needed please advise.

**Comment by chidg** [comment]
Thanks @rossbulat, this was actually an error on the Talisman extension side and has now been fixed
