### ISSUE TITLE
Add view to resolve extension url based on browser

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman-web#398]
In order to be able to provide a 'universal' browser extension url for either Firefox or Google web stores, it would be helpful if the web app provided a very simple endpoint that would redirect the user to either store based on detection of the browser type.

The URL for the Firefox store is: https://addons.mozilla.org/en-US/firefox/addon/talisman-wallet-extension/
And for the chrome store: https://chrome.google.com/webstore/detail/talisman-polkadot-wallet/fijngjgcjhjmmpcmkeiomlglpeiijkld

**Comment by alecdwm** [comment]
Closing because we've set up the download URL at https://talisman.xyz/download instead
