### ISSUE TITLE
CTA placeholders for when the user has no staking positions

### ISSUE THREAD

**Issue by SwamiTLSM** [TalismanSociety/talisman-web#404]
<img width="1046" alt="Screen Shot 2022-11-24 at 8 10 58 am" src="https://user-images.githubusercontent.com/93967089/203647052-c40aa991-f24e-441f-afb4-181c9b4a0906.png">

We should display here a CTA to begin staking when the user has no staking positions. 
Additionally, if there are no unstaking positions, we should hide the unstaking section.

**Comment by alecdwm** [comment]
Closing as completed!

<img width="659" src="https://github.com/user-attachments/assets/a33a5d30-2fbd-46aa-9e96-56408716bbe9" />
