### ISSUE TITLE
Investigate approach for concurrent chain connections

### ISSUE THREAD

**Issue by tien** [TalismanSociety/talisman-web#425]
# Current state

The new chain connection logic for our staking feature was built around a single global chain switcher, similar to every other DApps

# Requirements

- Use [polkadot-js/api](https://github.com/polkadot-js/api)
- Support multiple concurrent chain connection
- Subscription support
- Maintain good performance

**Comment by alecdwm** [comment]
Closing in favour of https://github.com/TalismanSociety/talisman-web/issues/1239
