### ISSUE TITLE
[BUG] Crowdloan made with Novawallet does not appear on Talisman

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#436]
Not sure if this is solved yet, so copying here for record
https://talisman.upvoty.com/b/bugs/crowdloan-made-with-novawallet-does-not-appear-on-talisman/

Problem:
User shuabyy#5096 reported that crowdloans done with Novawallet do not show on Talisman app
Setup:
Brave browser and mac os.

Thread discussion here:
[discord.com/channels/858891448271634473/912580578216407061/972795544596520960](https://discord.com/channels/858891448271634473/912580578216407061/972795544596520960)

**Comment by JAhimaz** [comment]
Both those crowdloans are present on our webapp. The user on discord has not responded on whether he is able to see it. Though, we had gone through adding most of them back in the config. Unless he reports again I think it is safe to say it has been fixed.
