### ISSUE TITLE
[BUG] NFT section on webapp doesn't display all NFT's when all accounts is selected

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#438]
**Description**
This might be designed to behave like this, but is a bit confusing to the user.
On: https://app.talisman.xyz/nfts, when you click All Accounts, it does not show the NFT's for All accounts, rather it prompts you to reselect an account. 

**Expected Behavior**
Either we need to remind the user that they can only view NFT's for specific accounts, or we need to show the NFT's for All Accounts. 

**Screenshots**
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/119995565/210497767-afd5cd8d-ce5e-4d80-8411-7a2a59a09308.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/119995565/210497820-1dbb8917-18e3-46e0-8fe3-a5eed78c12d8.png">
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/119995565/210497851-efb6b975-cb97-4b6b-b8dd-3e538a189e26.png">

**Comment by JAhimaz** [comment]
This should be fixed in Portfolio V2

**Comment by tien** [comment]
@JAhimaz cool can you validate and close this if that is the case?

**Comment by 0byt** [comment]
@JAhimaz plz check
