### ISSUE TITLE
Changing address doesn't always load the correct crowdloans

### ISSUE THREAD

**Issue by SwamiTLSM** [TalismanSociety/talisman-web#442]
Switching the address in the header while on the portfolio page sometimes fetches the incorrect crowdloans, or doesn't fetch them at all.

**Comment by tien** [comment]
Crowdloans work is not being prioritised right now, and this doesn't happen all the time, so relabelling this to a P3

**Comment by tien** [comment]
@obyttoby can you check how prevalence this is

**Comment by 0byt** [comment]
I can't replicate it at the moment @tien
