### ISSUE TITLE
Collapse crowdloan assets

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#470]
https://discord.com/channels/858891448271634473/1003673257335066715/1070183997814083725

having crowdloans collapse like into like the way assets do might be nice too for people that contribute from multiple accounts in the future
my cl section is 2x the size of the assets section despite being a much smaller portion of my holdings

![image](https://user-images.githubusercontent.com/119995565/216023289-c3a9ccf6-5ece-4a74-97de-e131219627d3.png)

**Comment by alecdwm** [comment]
From https://support.polkadot.network/support/solutions/articles/65000177342-crowdloans-faq

> With the introduction of [Agile Coretime](https://wiki.polkadot.network/docs/learn-agile-coretime) on Polkadot and Kusama, crowdloans have been deprecated.
> 
> The funds used to participate in previous crowdloans will remain locked until the corresponding slot lease expires, but there will no longer be any slot auctions or crowdloans in the future.
> 
> This article is temporarily available for reference.
