### ISSUE TITLE
Active account not shown in account selector

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#471]
Active account not shown in account selector, it's very confusing. Users often open the account selector to see the scope of accounts.

**Comment by tien** [comment]
@obyttoby can you check to see if this is still the case

**Comment by 0byt** [comment]
yes, it's still the case. For example, EVM and substrate account has the same name, but when i select one of them, it is unclear which one is selected in the dropdown. The user has to look at both icons and user names to figure out which is active. Perhaps we could do a different color background for the actual selected account?

<img width="595" alt="image" src="https://user-images.githubusercontent.com/119995565/235298651-6c8ac340-a09f-4f36-8457-ef973dc6a9b0.png">

**Comment by tien** [comment]
@obyttoby this is a design issue that we need to decide what the behaviour will be

cc @diogoalmeidaribeiro

**Comment by tien** [comment]
@obyttoby @diogoalmeidaribeiro any update on these?

**Comment by 0byt** [comment]
will schedule it in for when diogo is back!

**Comment by tien** [comment]
Moving this to a P3 in the meantime while we are still deciding

**Comment by tien** [comment]
cc @diogoalmeidaribeiro

**Comment by diogoalmeidaribeiro** [comment]
@0byt @tien option for selected account here: https://www.figma.com/file/flqMA1ke9Ts0ZlFtGeEb8y/Talisman-%7C-Web-App-Fixes?type=design&node-id=904-3938&mode=design&t=PvHg2tGdwlEgwG9x-4

**Comment by tien** [comment]
@tien rmb to do the work

**Comment by tien** [comment]
@diogoalmeidaribeiro Can you give an updated design for this? The item highlight has been changed to match latest menu item design.

**Comment by diogoalmeidaribeiro** [comment]
@tien I think we are still good to use the suggested active state like this: https://www.figma.com/design/flqMA1ke9Ts0ZlFtGeEb8y/Talisman-%7C-Web-App-Fixes?node-id=904-3938&t=1ZDquW738sO5PMvk-4

**Comment by alecdwm** [comment]
Fixed by https://github.com/TalismanSociety/talisman-web/pull/1237/commits/e851a59d32d48b0585d6c9408c875d424df3c9bd (included in https://github.com/TalismanSociety/talisman-web/pull/1237)
