### ISSUE TITLE
[BUG] Webapp throws Unhandled Thrown Error

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#477]
**Describe the bug**
Multiple users have reported Unhandled thrown error in new version of webapp. Alec's comment: "For the other guardians: I think this is being thrown by the chaindata backend
I saw it when trying to query chains and tokens"

**Links**
If applicable, add links to Sentry issues, Upvotey bug reports, or Discord messages.
https://discord.com/channels/858891448271634473/858914198465806377/1072095644438773821
https://discord.com/channels/858891448271634473/1071678136867102790
https://discord.com/channels/858891448271634473/1072079986103689306

**Screenshots**
If applicable, add screenshots/recordings to help explain your problem.
![webapp](https://user-images.githubusercontent.com/119995565/216965056-3ea8095f-4788-43c2-b287-e17914ee2953.png)

**Comment by tien** [comment]
@alecdwm going to fix this on the web app side by removing chain data dependency from staking
