### ISSUE TITLE
[Webapp] DEX Meta Aggregator

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#663]

**Comment by 0byt** [comment]
@chidg integration portion delayed 1 day due to Root account refactor, he will talk to @tien to see if it's more efficient to handover this part to tien instead

**Comment by 0byt** [comment]
FAQ sheet here (to be edited) @jonathanpdunne 
https://docs.google.com/document/d/1rOGGSqf1n10SHtevAkBZdhdMT_1ZsOD5b98GInPYiOk/edit

**Comment by tien** [comment]
Need to evaluate Privadex further
