### ISSUE TITLE
[Bug] Transaction history CSV download issues

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#693]
**Describe the bug**
Users cannot download CSV from TX history. 

**To Reproduce**
I cannot seem to reproduce it but download issues have been reported 3x, once by Sentinel, once by user, and once by Maarten from Astar, so there prob is indeed an issue, and prob chain related. 

**Expected behaviour**
Should be able to download CSV

**Links**
If applicable, add links to Sentry issues, Upvotey bug reports, or Discord messages.
https://discord.com/channels/858891448271634473/1110991464541995069/1110991464541995069

**Screenshots**
Screenshot from Maarten
![IMG_9142](https://github.com/TalismanSociety/talisman-web/assets/119995565/b3f3e4d6-6289-41f4-ae0e-949fb8ef0b0f)

Screenshot from user
<img width="564" alt="image" src="https://github.com/TalismanSociety/talisman-web/assets/119995565/f1736afc-f41f-4c4f-b982-dcee7dbef60b">

**Environment (please complete the following information):**

Talisman version: 1.16.3
Chrome: 113.0.5672.127 off 64

**Comment by tien** [comment]
TX history is currently being re-indexed, will check once that's finished

**Comment by tien** [comment]
Unable to reproduce, added exception logging with #711, so we'll know the issue when it does happens.

**Comment by tien** [comment]
No longer relevant with new tx history
