### ISSUE TITLE
Fix subsquid for tx history

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman-web#702]
- [x] Disable page on Portal
- [x] Fix on Subsquid
- [x] Wait for indexing
- [x] Re-enable page on Portal
- [ ] switch to subsquid's official multichain processors

**Comment by alecdwm** [comment]
Newly deployed subsquid URL: https://squid.subsquid.io/tx-history/v/v1/graphql
(fyi @tien)

As of now it's still indexing, you can see the status by going to https://txhistory-admin-ui.netlify.app/

**Comment by alecdwm** [comment]
Closing in favour of the new ex-history squid
