### ISSUE TITLE
Staking Dashboard / Webapp UI Cleaning

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#726]

**Comment by 0byt** [comment]
- [ ] UI-Fixes: Dropdown https://www.figma.com/file/Fr4XqmHaJcHm5r8JwUnaTb/Talisman-Sandbox?type=design&node-id=696%3A31347&mode=design&t=gWGDw0NFJGE45MlQ-1

**Comment by tien** [comment]
For linking to our TX history, more work is planned for TX history improvement. So we should build up on that.

cc @alecdwm
