### ISSUE TITLE
[Bug] Staking Dashboard - Asset selection should reflect on staking page

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#751]
🪲 Issue:
"Simulate rewards" window not affected by asset selection on the left, same for both up and down buttons. "Staking" button above also unresponsive to left-side asset selection. However, "Start staking" updates with left-side asset selection. 2 screenshot videos below!

☕  Expected behavior:
Upon modifying the assets on the left, the "simulate rewards" window should update accordingly.  For example, when I choose AZERO on the left, the 'simulate rewards' window should also display AZERO, just as the 'staking' window does.

From: Kanbeok

https://github.com/TalismanSociety/talisman-web/assets/119995565/470bee24-a2c1-4738-a16d-7d0774602910

**Comment by tien** [comment]
This has already been fixed
