### ISSUE TITLE
[Enhancement] TX History - Add empty state for search

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#761]
When connecting to a parachain (or other search parameter) where you have no transactions, the search results are blank. 
Let's add an empty state for this situation

<img width="1184" alt="2023-08-20_15 29 46" src="https://github.com/TalismanSociety/talisman-web/assets/119995565/685ff675-6b8c-4a59-af06-7fe4645ca8ae">

**Comment by diogoalmeidaribeiro** [comment]
https://www.figma.com/file/gaF0QAAaJ8Yjubyc1Ug1mf/Talisman-%7C-TX-History?type=design&node-id=1289-9382&mode=design&t=vr4Rcgt7eX3rh7PR-4 @0byt @tien a couple of options here
