### ISSUE TITLE
[Bug] TX History - Issue with date input & sorting

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#763]
Issue 1: No restrictions on date input digits
Issue 2: No restrictions on from / to date
Expected behavior:
Limit user input range and/or show error states (see if need design @diogoalmeidaribeiro )

<img width="655" alt="2023-08-20_15 34 58" src="https://github.com/TalismanSociety/talisman-web/assets/119995565/516cfb35-40bb-42a3-b032-5e9487cb30ed">

https://github.com/TalismanSociety/talisman-web/assets/119995565/2448440c-d48f-4a05-b986-ad6169e43c6f

**Comment by 0byt** [comment]
Other issue:
The dates in the date filter should be inclusive. Meaning if I select the today as the upper end of the date filter, users would expect to see todays transactions as well.

**Comment by tien** [comment]
> Other issue: The dates in the date filter should be inclusive. Meaning if I select the today as the upper end of the date filter, users would expect to see todays transactions as well.

Have pushed a fix for this
