### ISSUE TITLE
[Bug] TX History - Module list should be scrollable

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#767]
Currently the list is not scrollable or viewable. 

<img width="1440" alt="2023-08-20_15 52 09" src="https://github.com/TalismanSociety/talisman-web/assets/119995565/ac73dab5-79c1-4e2a-a845-74d5cd1cdc07">

**Comment by tien** [comment]
@0byt can you check whether this issue is still relevant? Scrolling does seem to work as expected.

**Comment by 0byt** [comment]
Yes, good now, thanks
