### ISSUE TITLE
[Bug] TX History - Unusual interaction on Proxy module 

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#768]
Strange delay on the backgroud when opening detailed transaction information on the "Proxy" module . 
This module tested only on Acala, so it needs testing on other parachains.

https://github.com/TalismanSociety/talisman-web/assets/119995565/8fd9f748-fd9a-4bd1-b9cb-eee86b93cba9

**Comment by tien** [comment]
@0byt Can you share the account or extrinsic hash with this issue?

**Comment by tien** [comment]
Oh right, that's some massive transaction. Hence, the lag when the app tried to render it.
Not really a bug, but a performance optimisation is needed. Will keep this in the backlog.
