### ISSUE TITLE
[Bug] TX History - Missing Zeitgeist transactions

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#769]
No transactions are displayed on Zeitgeist.
User's account:
https://zeitgeist.subscan.io/account/dE122WHGHxmG7hR4mXY9ADArAkrbVPzVecbZPfSUYTytAkbWR?tab=transfer

<img width="1281" alt="2023-08-20_16 06 34" src="https://github.com/TalismanSociety/talisman-web/assets/119995565/d466f58a-1c9a-4a93-939a-5a42fff7f3ae">

**Comment by tien** [comment]
@0byt so zeitgeist battery station is actually zeitgeist beta network n is completely different. Guessing Subsquid doesn't support zeitgeist mainnet as of now

**Comment by 0byt** [comment]
ok ok
