### ISSUE TITLE
[Enhancement] TX History - Colored icons for success / failed tx state

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#772]
Would be cool to see a colorful logo of a successful or failed transaction. I think it would be more intuitive to understand.

![1 1](https://github.com/TalismanSociety/talisman-web/assets/119995565/0f3fff27-4bea-44cd-94c2-477c982f9cd6)
![1 2](https://github.com/TalismanSociety/talisman-web/assets/119995565/d2e56268-966f-4c43-9277-dddd9a463e71)

**Comment by 0byt** [comment]
Also consider adding tx state to the main tx list, cc @diogoalmeidaribeiro 

![2](https://github.com/TalismanSociety/talisman-web/assets/119995565/c8148284-98f9-45b2-b88d-92c8b65d3e15)

**Comment by tien** [comment]
Have added color indicator to the modal/dialog view
