### ISSUE TITLE
[Bug] TX History - Error state for invalid search string

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#773]
Users can input endlessly long strings with no restrictions
Some options:
1/ Consider limiting the search strings to several types and then provide error state when string does not fall within these options (if possible)
2/ Define a few input rules, like no spaces, string length, etc.
3/ Display error or result state if there are no matching searches (we need to do this anyway)

![3 1](https://github.com/TalismanSociety/talisman-web/assets/119995565/944313ca-9756-4a90-b23a-ea516e79794f)
![3 2](https://github.com/TalismanSociety/talisman-web/assets/119995565/d1c3ec33-2b92-4771-9b21-fdf251ba96d0)

**Comment by diogoalmeidaribeiro** [comment]
https://www.figma.com/file/gaF0QAAaJ8Yjubyc1Ug1mf/Talisman-%7C-TX-History?type=design&node-id=1289-9382&mode=design&t=vr4Rcgt7eX3rh7PR-4 @0byt @tien

**Comment by tien** [comment]
Have added simple error prompt for invalid search
