### ISSUE TITLE
[Bug] TX History - Other scroll issues

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#774]
When you reach the border of the "Chain" and "Module" window and keep turning it down, then the main page of the Transaction History starts dropping.

https://github.com/TalismanSociety/talisman-web/assets/119995565/20f33fbc-1a2f-4cd7-a1d3-2da1bfaa60c9

**Comment by tien** [comment]
This is kind of typical behaviour of drop down select tbh. As you scroll down, the select dropdown will try to fill the newly available state
