### ISSUE TITLE
[Enhancement] TX History - Too many chains/modules to scroll through in filter

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#776]
From multiple users: it would be beneficial to view the complete name of the chain/module without requiring horizontal scrolling (Screenshot 2A and 2B in 'To Reproduce'). cc @diogoalmeidaribeiro 

It would be helpful if the app could recognize which chains/modules a particular address had interacted with and only present those specific chains/modules as filter options, instead of displaying all of them.

2A - Horizontal scrolling for chain
![asasassasasa3](https://github.com/TalismanSociety/talisman-web/assets/119995565/39f3aaee-8986-4e08-a6ea-c313f6f93791)

2B - Horizontal scrolling for Module
![asasassasasa](https://github.com/TalismanSociety/talisman-web/assets/119995565/8a60968d-6796-41cf-9e5c-80c166b2c92a)

**Comment by tien** [comment]
I have created a detached selector specifically these
<img width="385" alt="image" src="https://github.com/TalismanSociety/talisman-web/assets/19813755/f4504df4-3fcd-41c4-900c-b06975211ae4">

As for:
> It would be helpful if the app could recognize which chains/modules a particular address had interacted with and only present those specific chains/modules as filter options, instead of displaying all of them.

 Not possible with our current data structure & indexing

**Comment by tien** [comment]
Additionally, have added type ahead feature to select component. So matching items will be focused as the user type.

**Comment by 0byt** [comment]
Great
