### ISSUE TITLE
[Enhancement] XCM - show balances on assets list

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman-web#777]
From Fritz:
Asset transfer/ teleport: Additionally to the available chains that support the selected assets I would like to have the amount I have on each of those already displayed in the dropdown aswell. I feel thats handy if I just quickly want to get funds to my chain of interested I don't have to manually iterate through all of those trying to find the one which has enough balance for me to transfer. Especially with xcm being used more I think assets get split up wide and far so that this feature would allow for some more convenience.

**Comment by tien** [comment]
With the xcm library, available balance are currently lazily fetch once a route is selected. Can probably get the balance from our balances lib instead.
